import type { NextPage } from "next";
import Head from "next/head";
import Director from "../components/Director";

import packageJson from "../package.json";
const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Canvas Drawings</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        style={{
          position: "absolute",
          left: "1vw",
          top: "1vh",
          padding: "1em",
          border: "2px solid black",
          borderRadius: "64px",
        }}
      >
        {packageJson.version}a
      </div>
      <main
        style={{
          display: "flex",
          flexDirection: "row",
          justifyContent: "center",
          alignItems: "center",
          height: "100%",
          padding: 0,
          margin: 0,
        }}
      >
        <Director></Director>
      </main>
    </div>
  );
};

export default Home;
